
# --- !Ups

ALTER TABLE dote RENAME frown_count TO scowl_count;

ALTER TABLE dote ALTER COLUMN person_id SET NOT NULL;
ALTER TABLE dote ALTER COLUMN dotable_id SET NOT NULL;
ALTER TABLE dote ALTER COLUMN smile_count SET NOT NULL;
ALTER TABLE dote ALTER COLUMN cry_count SET NOT NULL;
ALTER TABLE dote ALTER COLUMN laugh_count SET NOT NULL;
ALTER TABLE dote ALTER COLUMN scowl_count SET NOT NULL;

# --- !Downs

ALTER TABLE dote ALTER COLUMN person_id DROP NOT NULL;
ALTER TABLE dote ALTER COLUMN dotable_id DROP NOT NULL;
ALTER TABLE dote ALTER COLUMN smile_count DROP NOT NULL;
ALTER TABLE dote ALTER COLUMN cry_count DROP NOT NULL;
ALTER TABLE dote ALTER COLUMN laugh_count DROP NOT NULL;
ALTER TABLE dote ALTER COLUMN scowl_count DROP NOT NULL;

ALTER TABLE dote RENAME scowl_count TO frown_count;
