package resonator.web

import scalacss.internal.mutable.StyleSheet
import CssSettings._
import resonator.web.constants.MuiTheme

import scalacss.internal.Attr

/**
  * CSS rules for specific elements, class names for these styles are generated by ScalaCss
  * dynamically so they must be referred to via scala code.
  */
object SharedStyles extends StyleSheet.Inline {
  import dsl._

  val spacingUnit = 8 px

  val paperContainer = style(
    padding(spacingUnit * 2)
  )

  val centerContainer = style(
    margin.auto,
    display.table
  )

  val centerTextContainer = style(
    alignItems.center,
    display.flex
  )

  val mainContentContainer = style(
    margin(spacingUnit * 3)
  )

  val centerItem = style(
    position.relative,
    margin.auto
  )

  val tileContainer = style(
    marginTop(spacingUnit * 3),
    marginBottom(spacingUnit * 3)
  )

  val plainAnchor = style(
    textDecorationLine.none
  )

  val centerText = style(
    textAlign.left,
    display.grid,
    alignContent.center,
    alignItems.center
  )

  val detailsFieldContainer = style(
    textAlign.left,
    marginBottom(spacingUnit * 2),
    marginLeft(spacingUnit * 2),
    marginRight(spacingUnit * 2),
    paddingLeft(spacingUnit * 2),
    paddingRight(spacingUnit * 2)
  )

  val entityDetailsContainer = style(
    margin(spacingUnit * 2)
  )

  val roboto = fontFace("roboto")(
    _.src("url(/assets/fonts/roboto/Roboto-Regular.ttf)")
  )

  val robotoSlab = fontFace("robotoSlab")(
    _.src("url(/assets/fonts/robotoSlab/Roboto-Regular.ttf)")
  )

  val cutePunkFf = fontFace("cutePunk")(
    _.src("url(/assets/fonts/cutepunk/Cutepunk_Regular.otf)")
  )

  val jaapokkiRegularFf = fontFace("jaapokkiRegular")(
    _.src("url(/assets/fonts/jaapokki/regular/web/jaapokki-regular.ttf)")
  )

  val jaapokkiEnchanceFf = fontFace("jaapokkiEnchance")(
    _.src("url(/assets/fonts/jaapokki/enchance/web/jaapokkienchance-regular.ttf)")
  )

  val jaapokkiSubtractFf = fontFace("jaapokkiSubtract")(
    _.src("url(/assets/fonts/jaapokki/subtract/web/jaapokkisubtract-regular.ttf)")
  )

  val syntesiaFf = fontFace("syntesia")(
    _.src("url(/assets/fonts/syntesia/syntesia.ttf)")
  )

  val rudeFf = fontFace("rude")(
    _.src("url(/assets/fonts/rude/rude.ttf)")
  )

  val aileronHeavyFf = fontFace("aileronHeavy")(
    _.src("url(/assets/fonts/aileron/Aileron-Heavy.ttf)")
  )

  val aileronSemiBoldFf = fontFace("aileronSemiBold")(
    _.src("url(/assets/fonts/aileron/Aileron-SemiBold.ttf)")
  )

  val aileronRegularFf = fontFace("aileronRegular")(
    _.src("url(/assets/fonts/aileron/Aileron-Regular.ttf)")
  )

  val ssEmojiFf = fontFace("ssEmoji")(
    _.src("url(/assets/fonts/ss-emoji/ss-emoji-adobe-mozilla.ttf)")
  )

  val rogueSansExtBoldIt = fontFace("rogueSansExtBoldIt")(
    _.src("url(/assets/fonts/rogue-sans/rogue-sans-ext-bold-it.otf)")
  )

  val siteRoot = style(
    padding(0 px)
  )

  val episodeList = style(
    height(100 %%),
    overflow.auto
  )

  val linearProgress = style(
    width(100 %%)
  )

  val podcastDetailsTabContentsContainer = style(
    height(400 px)
  )
}
